{
    "name": "Customer Base",
    "version": "17.0.1.0.4",
    "author": "dynapps",
    "website": "https://www.dynapps.eu",
    "category": "Hidden",
    "license": "LGPL-3",
    "depends": [
        "account",
        "account_followup",
        "account_intrastat",
        "auditlog",
        "base",
        "contacts",
        "dyn_analytics",
        "dyn_block_uninstall",
        "dyn_healthcheck",
        "mail",
        "mrp",
        "purchase",
        "printnode_base",
        "product",
        "sale",
        "sale_procurement_group_by_line",
        "sale_stock",
        "sale_management",
        "server_environment_ir_config_parameter",
        "smile_audit",
        "web_environment_ribbon",
        "web_m2x_options",
    ],
    "data": [
        "data/auditlog_rule_data.xml",
    ],
    "installable": True,
    "dyn_required": True,
}
