{
    "name": "Eurocable Stock",
    "version": "17.0.0.1.7",
    "author": "dynapps",
    "category": "Stcok",
    "license": "LGPL-3",
    "depends": ["xx_base", "eurocable_sale"],
    "data": [
        "security/ir.model.access.csv",
        "report/report_picking.xml",
        "report/report_delivery_document.xml",
        "views/stock_move_line_views.xml",
        "views/stock_picking_views.xml",
        "views/product_views.xml",
        "report/green_card_label.xml",
        "views/res_company_view.xml",
        "views/stock_picking_label_layout_views.xml",
        "report/stock_report_views.xml",
        "report/all_report.xml",
    ],
}
