{
    "name": "Eurocable Sale",
    "version": "17.0.0.1.3",
    "author": "dynapps",
    "category": "Sale",
    "license": "LGPL-3",
    "depends": ["xx_base", "eurocable_mrp"],
    "data": [
        "security/ir.model.access.csv",
        "wizard/add_fixed_sale_phrase.xml",
        "wizard/sales_wizard_views.xml",
        "wizard/sale_make_invoice_advance_views.xml",
        "views/fixed_sale_phrase_views.xml",
        "views/sales_views.xml",
        "views/partner_views.xml",
        "views/product_template_view.xml",
        "views/document_type.xml",
        "views/menus.xml",
        "data/template_certificate.xml",
        "report/certificat_report.xml",
        "report/sale_report_template.xml",
        "report/report_packing_list.xml",
    ],
}
