name: pre-commit-ci
on:
  pull_request:
jobs:
  pre-commit-ci:
    name: Lint changed backend files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +${{github.base_ref}}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --from-ref origin/${{github.base_ref}} --to-ref HEAD
